# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bleve_pb2 as bleve__pb2


class SearchStub(object):
  """The service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoSearch = channel.unary_unary(
        '/protobufs.Search/DoSearch',
        request_serializer=bleve__pb2.SearchRequest.SerializeToString,
        response_deserializer=bleve__pb2.SearchReply.FromString,
        )


class SearchServicer(object):
  """The service definition.
  """

  def DoSearch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SearchServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoSearch': grpc.unary_unary_rpc_method_handler(
          servicer.DoSearch,
          request_deserializer=bleve__pb2.SearchRequest.FromString,
          response_serializer=bleve__pb2.SearchReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protobufs.Search', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
